VVS279_KeyGenerator_02_07_2019
thisisdg/python-port-scanner pull request #3
Opened 2019-07-02 12:18 UTC by VVS279

Code standardized.

2019-07-03 08:25 UTC, thisisdg-zz requested changes
Remove underscores from all function names and use camel casing.

Also remove pycache directory from the commit, as it is created automatically whenever the library is called.

2019-07-03 08:25 UTC, thisisdg commented on __init__.py
> +print(sys.path)
Add a blank line at the end of the file

2019-07-03 09:08 UTC, VVS279 commented
Changes have been done in the __init__.py file.

2019-07-03 09:42 UTC, VVS279 reviewed
Changes are done.

2019-07-03 09:42 UTC, VVS279 commented on __init__.py
> +print(sys.path)
Changes have been done.

2019-07-11 16:29 UTC, thisisdg commented on test/KeyTest.py
> +print(KeyGenUtils.__get_current_user__() + "   " + key)
_get_current_user_() is custom function right, use camelCasing here, also for all the above functions too. I think these are the last changes that you need to revise.

2019-07-11 16:35 UTC, thisisdg-zz requested changes
Use camel casing for function and variable names, and not for standard syntax and constant names.

2019-07-11 16:35 UTC, thisisdg commented on test/KeyTest.py
> +print(KeyGenUtils.__get_current_user__() + "   " +
use camel casing

2019-07-11 16:35 UTC, thisisdg commented on lib/KeyGenUtils.py
> +    return __unpad__(to_decode)
use camel casing

2019-07-11 16:35 UTC, thisisdg commented on lib/KeyGenUtils.py
> +def __aes_encode__(to_encode):
use camel casing

2019-07-11 16:35 UTC, thisisdg commented on lib/KeyGenUtils.py
> +def __sha256_encode__(toencode_string):
use camel casing for all the functions here in this file

2019-07-11 16:35 UTC, thisisdg commented on lib/KeyGenUtils.py
> +        'USERNAME': str(__get_current_user__()),
camel casing

2019-07-11 16:35 UTC, thisisdg commented on lib/KeyGenUtils.py
> +    json_string = json.dumps(params)
camel casing, means remove underscores, and write the name as jsonString instead of json_string. Change this for all.

2019-07-11 16:35 UTC, thisisdg commented on constants/KeyGenConst.py
> +SECRET_KEY = b'Iy9UErx4chg4fdA6'
no need to change this, this is okay.

2019-07-11 16:35 UTC, thisisdg commented on __init__.py
> +sys.path.append(os.path.abspath(os.path.dirname(__file__) + '/' + './'))
this is okay too, as this is standard syntax

2019-09-11 10:42 UTC, merged